
"""
Parameters for server
"""

from asyncio.windows_events import NULL

SERVER_VERSION = 3
DEFAULT_PORT = '1234'
# in bytes
CHUNK_SIZE = 1024
CKSUM_SIZE = 4
REQUEST_HEADER_SIZE = 23
RESPONSE_HEADER_SIZE = 7
PUB_KEY_SIZE = 160
MAX_USERNAME = 255
MAX_FILENAME = 255
UUID_SIZE = 16
MSG_TYPE_SIZE = 1
CONTENT_SIZE = 4
MSG_ID_SIZE = 4
EMPTY_PAYLOAD = 0
IV = b'0000000000000000'  # '\0'

SERVER_DB = 'server.db'
MAX_ACCEPTED_CONNECTIONS = 100

# register request
REGISTER_REQUEST_CODE = 1100
REGISTER_REQUEST_PAYLOAD = MAX_USERNAME + PUB_KEY_SIZE
REGISTRATION_SUCCESS = 2100  # successful registration
REGISTRATION_FAILED = 2101  #  registration not success


# public key request
CLIENT_SEND_PUBLIC_KEY = 1101
PUBLIC_KEY_RESPONED_AES = 2102
CLIENT_SEND_ENCRYPTED_FILE = 1103
CRC_RESPONED = 2103
CRC_SUCCESS = 1104
CRC_FAILED = 1105
CRC_FAILED_END_PROGRAM = 1106
END_PROCESS = 2104


SERVER_ERROR_CODE = 9000
SERVER_ERROR_SIZE = 0

CRC_RESPONSE_PAYLOAD =  UUID_SIZE + CONTENT_SIZE + MAX_FILENAME + CKSUM_SIZE